name: Weekly Lake Detection

on:
  schedule:
    # Every Monday at 00:00 UTC
    - cron: "0 0 * * 1"
  workflow_dispatch:  # allows manual runs from the UI

jobs:
  run-lake-detection:
    runs-on: ubuntu-latest

    env:
      GEE_API_KEY: ${{ secrets.GEE_API_KEY }}
      DRIVE_SERVICE_ACCOUNT: ${{ secrets.DRIVE_SERVICE_ACCOUNT }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt;

      - name: Run lake detection script
        run: |
          python lakedetection.py